//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiTokenAuthScopes = "ApiTokenAuth.Scopes"
)

// Defines values for ExternalApplicationStatus.
const (
	ACCEPTED ExternalApplicationStatus = "ACCEPTED"
	PENDING  ExternalApplicationStatus = "PENDING"
	REJECTED ExternalApplicationStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ExternalApplicationStatus enum.
func (e ExternalApplicationStatus) Valid() bool {
	switch e {
	case ACCEPTED:
		return true
	case PENDING:
		return true
	case REJECTED:
		return true
	default:
		return false
	}
}

// Defines values for SortType.
const (
	ASC  SortType = "ASC"
	DESC SortType = "DESC"
)

// Valid indicates whether the value is a known member of the SortType enum.
func (e SortType) Valid() bool {
	switch e {
	case ASC:
		return true
	case DESC:
		return true
	default:
		return false
	}
}

// AssignManagerModel defines model for AssignManagerModel.
type AssignManagerModel struct {
	DirectionManagerId *int64 `json:"directionManagerId,omitempty"`
	ManagerId          int64  `json:"managerId"`
}

// CreateExternalApplicationModel defines model for CreateExternalApplicationModel.
type CreateExternalApplicationModel struct {
	AdditionalInformation *string `json:"additionalInformation,omitempty"`
	Email                 string  `json:"email"`
	ExpectedResults       string  `json:"expectedResults"`
	FullName              string  `json:"fullName"`
	IsPayed               bool    `json:"isPayed"`
	OrganisationName      string  `json:"organisationName"`
	OrganisationUrl       *string `json:"organisationUrl,omitempty"`
	Phone                 *string `json:"phone,omitempty"`
	ProjectName           string  `json:"projectName"`
	TypeId                int64   `json:"typeId"`
}

// ExternalApplicationModel defines model for ExternalApplicationModel.
type ExternalApplicationModel struct {
	AdditionalInformation *string                   `json:"additionalInformation,omitempty"`
	ApplicationId         int64                     `json:"applicationId"`
	Email                 string                    `json:"email"`
	ExpectedResults       string                    `json:"expectedResults"`
	Initiator             string                    `json:"initiator"`
	IsPayed               bool                      `json:"isPayed"`
	OrganisationName      string                    `json:"organisationName"`
	OrganisationUrl       *string                   `json:"organisationUrl,omitempty"`
	Phone                 *string                   `json:"phone,omitempty"`
	ProjectName           string                    `json:"projectName"`
	Status                ExternalApplicationStatus `json:"status"`
	TypeName              string                    `json:"typeName"`
}

// ExternalApplicationPreviewModel defines model for ExternalApplicationPreviewModel.
type ExternalApplicationPreviewModel struct {
	DateUpdated           time.Time                 `json:"dateUpdated"`
	ExternalApplicationId int64                     `json:"externalApplicationId"`
	Initiator             string                    `json:"initiator"`
	OrganisationName      string                    `json:"organisationName"`
	ProjectName           string                    `json:"projectName"`
	RejectionMessage      *string                   `json:"rejectionMessage,omitempty"`
	Status                ExternalApplicationStatus `json:"status"`
	TypeName              string                    `json:"typeName"`
}

// ExternalApplicationStatus defines model for ExternalApplicationStatus.
type ExternalApplicationStatus string

// ExternalApplicationsModel defines model for ExternalApplicationsModel.
type ExternalApplicationsModel struct {
	Applications []ExternalApplicationPreviewModel `json:"applications"`
	Count        int64                             `json:"count"`
}

// ProjectTypeModel defines model for ProjectTypeModel.
type ProjectTypeModel struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// ReasonModel defines model for ReasonModel.
type ReasonModel struct {
	Reason string `json:"reason"`
}

// SortType defines model for SortType.
type SortType string

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	// Login Логин пользователя
	Login string `json:"login"`

	// Password Пароль пользователя
	Password string `json:"password"`
}

// ListExternalApplicationsParams defines parameters for ListExternalApplications.
type ListExternalApplicationsParams struct {
	// Active Находится ли в статусе "PENDING"
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// Search Поиск по названию заявки или ФИО инициатора
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// ProjectTypeId Поиск по типу проекта
	ProjectTypeId *int64 `form:"projectTypeId,omitempty" json:"projectTypeId,omitempty"`

	// SortByDateUpdated Если этот флаг передан, то нужно сортировать проекты в указанном порядке сортировки
	SortByDateUpdated *SortType `form:"sortByDateUpdated,omitempty" json:"sortByDateUpdated,omitempty"`
	Limit             *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset            *int      `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateExternalApplicationJSONRequestBody defines body for CreateExternalApplication for application/json ContentType.
type CreateExternalApplicationJSONRequestBody = CreateExternalApplicationModel

// RejectExternalApplicationJSONRequestBody defines body for RejectExternalApplication for application/json ContentType.
type RejectExternalApplicationJSONRequestBody = ReasonModel

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вход в систему
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)
	// Подать заявку на проект от внешнего инициатора (доступна всем пользователям)
	// (POST /project/application/external)
	CreateExternalApplication(w http.ResponseWriter, r *http.Request)
	// Получить список внешних заявок (доступна пользователям с ролью "ADMIN")
	// (GET /project/application/external/list)
	ListExternalApplications(w http.ResponseWriter, r *http.Request, params ListExternalApplicationsParams)
	// Получить внешнюю заявку (доступна пользователям с ролью "ADMIN")
	// (GET /project/application/external/{applicationId})
	GetExternalApplication(w http.ResponseWriter, r *http.Request, applicationId int64)
	// Принять внешнюю заявку (доступна пользователям с ролью "ADMIN")
	// (POST /project/application/external/{applicationId}/accept)
	AcceptExternalApplication(w http.ResponseWriter, r *http.Request, applicationId int64)
	// Отклонить внешнюю заявку (доступна пользователям с ролью "ADMIN")
	// (POST /project/application/external/{applicationId}/reject)
	RejectExternalApplication(w http.ResponseWriter, r *http.Request, applicationId int64)
	// Возвращает все типы проектов (доступна всем пользователям)
	// (GET /project/type)
	ListProjectTypes(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExternalApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateExternalApplication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExternalApplication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExternalApplications operation middleware
func (siw *ServerInterfaceWrapper) ListExternalApplications(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExternalApplicationsParams

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "projectTypeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "projectTypeId", r.URL.Query(), &params.ProjectTypeId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectTypeId", Err: err})
		return
	}

	// ------------- Optional query parameter "sortByDateUpdated" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortByDateUpdated", r.URL.Query(), &params.SortByDateUpdated, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortByDateUpdated", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExternalApplications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExternalApplication operation middleware
func (siw *ServerInterfaceWrapper) GetExternalApplication(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId int64

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", r.PathValue("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExternalApplication(w, r, applicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptExternalApplication operation middleware
func (siw *ServerInterfaceWrapper) AcceptExternalApplication(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId int64

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", r.PathValue("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptExternalApplication(w, r, applicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectExternalApplication operation middleware
func (siw *ServerInterfaceWrapper) RejectExternalApplication(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId int64

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", r.PathValue("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectExternalApplication(w, r, applicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectTypes operation middleware
func (siw *ServerInterfaceWrapper) ListProjectTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/project/application/external", wrapper.CreateExternalApplication)
	m.HandleFunc("GET "+options.BaseURL+"/project/application/external/list", wrapper.ListExternalApplications)
	m.HandleFunc("GET "+options.BaseURL+"/project/application/external/{applicationId}", wrapper.GetExternalApplication)
	m.HandleFunc("POST "+options.BaseURL+"/project/application/external/{applicationId}/accept", wrapper.AcceptExternalApplication)
	m.HandleFunc("POST "+options.BaseURL+"/project/application/external/{applicationId}/reject", wrapper.RejectExternalApplication)
	m.HandleFunc("GET "+options.BaseURL+"/project/type", wrapper.ListProjectTypes)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xab2/b1vX+KsT99UWLn1ypSbYOeuc6RuE2yYw4xQZUHsBI1zIzimTJqzSGIcCSmqWB",
	"s7gtNqzo1hjrBuwtrViNYlvKVzj3Gw3nXIoiqUtZ/pO2K/omtlnpnj/3PM95zmG3WdVteK7DHRGw8jYL",
	"qpu8YdKvi0Fg1Z2bpmPWuX/TrXEbn5q1miUs1zHtVd/1uC8sHrDyhmkHvMC8xKNtVrN8XsXPRmes1PDp",
	"hus3TMHKzHLEr6+xAnOatm3etTkrC7/JC0xYAv9gKzVD7sguHMEIejCCQxjIDvThWO4ZMIQQXskdCKEH",
	"x9CHIQzkHiswseVxdTavc5+1Cqwx0/hcxtDQCPpwJDsQaoy0CsznnzQtn9dY+eOExfX4s+7de7wq0J8l",
	"n5uCLz8Q3HdMe9HzbKtqUpbOkeLJR1ccFZvlOvgfGuaDG9ypi01WfudXpVJ+luEvMIJXMIJjyqGK+Qnm",
	"FyMfwFB+BiO5AycQyj+lkxwI33LqGBNvmJY9bTZh5Qs4lDvQl20DjclHsiN3DXgBIRxBCC/kIxjgb9rD",
	"H3i8KnjtNg+atqrSqehiO8/gexjAIYTQhxO5C30DzcIL2cWw8P7Qss7MRtO2b5kNPjOMf8PX8GxOv61g",
	"1dziVHbx9/fJm8Mo4SE8R0dlR7Yx2ccwMOgyjtHL5KF3XdfmpoOnun7ddKyALvpUd79FH6EHId4t9A26",
	"yefRny/UjcJA53zSzEc+3W1uBf1TtuUuHGMeCJiGbEMIL2XnDPa8TdfhOiueKRAprMz+UKn8/7tGpfJm",
	"pVLbvtqqVN4y1G8L+OPK+McbLJWAEZxAX+4YqrKhj+VMTs53iZ7vInDPnukczpicjA/mIKUODOAVuntG",
	"EorLeYxOTemkw4tdmobcpJh1jDaLy+akq9fKTubEr9MTDj0YQl9+jv/CS6oSuQc9OErWbaK9xNR3CtUN",
	"KACsf8Q2+jwv2V0Ct1mOJSxTuH7qvK+zLs1RtT8cqf2cSGwuPpqzQjKMdAEGCoQpmlRib/h8g5XZ/xUn",
	"YrAYKcGiBt1r6osRiU158h1S1qn2M3yVBmmyZM9IYGPSy6WwOPA5uWzV5/ct/mkOpdVMwT/y8N80teCT",
	"BWEptyZsRhhAQBzAkKRmLF5zqCZJDVOuXT6dXR5TvCZMX175+/xeNJ7wIDDrs4GLHDcgoUBYHckOHMEx",
	"QXfe+3tdcMtGfqpkyEGgvr5mQCwJUQ00k8g4K+bW4lxxp9lA71aXb11fufU+K7DFpaXl1TvL11mB3V7+",
	"YHkJf13X5FtzbJCnSxIfwb8twRvnuakUVbQS5fNVjEKqTW2lmL5vbuG3qm7TETOBDd9Qq8WC7Mu27ODI",
	"Ojl1BEckPQz5GQyUNMDZ1oADVAuG7MpH8kviIdtqWOJ0LakcKqTTpLvJVVUqd7Y8npNp6xIVb4E5WSzs",
	"R1JxhFkewIncOzccLKxaMqCL9DY3g/ON7D59MzNMvJsaJi5MNplQIpO6ONZcn64rCbXFtSVWYNeX15Y0",
	"uEIi49Wmb4mtNQSCCmrRs+64f+TOYhOj2WYWDmyb3Kxxf5zFMvv9wuLqysKd3364fCtR9Z71Id9irRY1",
	"nw2XeioPqr7lqeGAwT9gBIdK5FJdowTG7BgkLWUHDpRayiBgmLlz+myyIQ7kQwIDhIShIU2BI+i9bcB/",
	"aNgg/YeVdEBl1ae2Qs7sxB28r9TtgORiBO+eEo8nysIO2TiCUD5MQziEA7rivuwYCyQIyQ+1gFIsQWqf",
	"TmUFdp/7gUrJO2+X3i5Rk/W4Y3oWK7Or9Ijm5U26kqLt1i2qM88NhCatX0Av0pnYctEqzg9RinHKih/G",
	"ezBkGazD5zR6dekCXkFI6TiWTxk55MfShN0gF1Qx8kC859a20JGq6wiuKC5BKcV7ES4UwZ4RVnG0mSj/",
	"PnY3Ny5WSI31tE6aUh1mEHzq+jWNgf04/icXMJFBrB0lLrY7jd30V1Cu0IPAc51ApeRKqXSmbKcTKhDP",
	"0/F+8Ls7C1SkR8hFsyKejlATQfpwTPW10juaLD+Tn8MADtR4FqYqdywWiZqajYbpb1HLlQ8RqhEaBwQt",
	"nJu76JpZDzDN8CV2RAJwKNuIZ/yYfMLW8bBipHyKybSNVdIMYH0nuxmiQeU90GhonARpdA6xISNBtaOx",
	"YCi78qluw/HUQBAmW1k/5sF4IS73iFQmTQKxSkPtDpFdG07wC2R8zC5p5OZuqS+A5lli6pSt+Guo9mkN",
	"khVBU+UJX8EIXlAOH6sdh4GCpY1PI6bG28uMWVTTpdNqGvX7sVrvqHrGy6flyZD6Qlc+Hms9LA35mKoq",
	"2thlSn8/6pHE5lM1MLMn9uE51pdmF2G8CYcRPrrwSp3Uk23EVC4LwMlbSbT9Lc5KqHFlwZjIZLmX1jjh",
	"HIgs2paCY50LLU+ji9iKB5QY2Y7aNomFtCpIC4k0gWjAcsMKhG7aIAL3zQYX3McMTPn0LYqC8dumxL4M",
	"LUb7vC6m2KiM558Ko8GLldknTe5vTcSVWRXWfRy7JhVe4xtm0xbxLJtZu7UK2hxhSqL5gd6yxaMlUk+i",
	"ruP6jN6J6NdXOlcDbvrVzZSrU3N3tnec5qpS+VjiWZWv88CbzCk04s5ghRzPEqPSlGt/lW3KjPwzJaKD",
	"cxjtRVOMD8MCeo1Zll34HpmDqETuYCwUxESRTWKSu1QeXfXqIuYchUG5I/fgEFvz9FFqUNDeh+uL97au",
	"p8f1uVg7nh4oDbqzxxOmpiqvlPTZ1B3jbmwEPOcc3THrF2wOZ5z7g0SXyiqaxMBEFJAelT5eR18z3H0u",
	"mtLQcy4rG7JtjEWrfGpU2OL1myu3KizF1t+oZaUS/Clb85Dxdmqh28rl5ToX0dYgkU9Nit/nQq9G0lSc",
	"+7EMEVOR4ayUYNDM3istNwpnkg4/cP3NKL88Qb2vrY0nJDcyAnukOoA666rmrH/NmBnVeKuKDbsFjrQn",
	"UbNokwSdtAsycE1jICMc+qozvYRD0q/hhUE2wZV8mmpzsnv5uMoXOdOi6BxIK5rVKvfEjPlkP2pC8f/n",
	"MjN+LIG0HAmTciQrVjDoaEFLWiUNz0Xy7SeM0GxlE/0qxh3lK3ltfWaV3UxR9wtOtTilyBAoPzuUqrdP",
	"PyJKx+9ONCi9Tb79ZFB6+duG5PZ+/tXCpXDDFC0MxxvjPG6IB63RzH3BLxSipZBniZcn/1vNXkSvZXLW",
	"Gfg99b4gMyOkIpC78uH4FdgIeunxeAQ97S4j8RovYBdUsnO9Sp16b9jKvhXNm6wS+17awvVS2zm1oBov",
	"B3anov/xd1pUzf79MZ02fZuV2aYQXrlYtN2qaW+6gSj/plQqFVlrvfXfAAAA//+wttfkry0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
